services:

  website:
    build: 
      dockerfile: Dockerfile.app
      context: ./

    volumes:
      - ./static:/static
      - ./templates:/templates
      - ./app.py:/app.py
      
    ports:
      - "5000:5000"

