FROM php:7.2-apache
USER root
COPY index-no-security.php /var/www/html/index.php
COPY upload.php /var/www/html/upload.php

RUN mkdir /var/www/html/uploads

RUN chown www-data:www-data /var/www/html/*
RUN chown www-data:www-data /var/www/html/uploads

EXPOSE 80

