// docker compose exec server node seed.js

const mongoose = require("mongoose");
const SHA256 = require("crypto-js/sha256");
const dotenv = require("dotenv");
dotenv.config();

const User = require("./models/user");
const Categories = require("./models/cookbook/categories");
const Recipe = require("./models/cookbook/recipe");

const MONGODB_URI = process.env.MONGODB_URI || "mongodb://127.0.0.1:27017/cookbook";

async function seed() {
	await mongoose.connect(MONGODB_URI, {
		useNewUrlParser: true,
		useUnifiedTopology: true,
		useCreateIndex: true,
		useFindAndModify: false,
	});
	
	console.log("Connected to MongoDB");
	
	await User.deleteMany({});
	await Categories.deleteMany({});
	await Recipe.deleteMany({});
	console.log("Cleared existing data");
	
	const user1 = await User.create({
		firstname: "Max",
		lastname: "Mustermann",
		street: "Musterstraße 1",
		postcode: "78120",
		city: "Furtwangen",
		country: "Deutschland",
		phone: "0123456789",
		email: "max@example.com",
		password: SHA256("password123").toString(),
		savedRecipes: [],
	});
	console.log("Created test user 1 (max@example.com / password123)");
	
	const user2 = await User.create({
		firstname: "Anna",
		lastname: "Schmidt",
		street: "Hauptstraße 5",
		postcode: "78120",
		city: "Furtwangen",
		country: "Deutschland",
		phone: "0987654321",
		email: "anna@example.com",
		password: SHA256("password123").toString(),
		savedRecipes: [],
	});
	console.log("Created test user 2 (anna@example.com / password123)");
	
	const categories = await Categories.insertMany([
		{ name: "vegan" },
		{ name: "vegetarisch" },
		{ name: "fleisch" },
		{ name: "fisch" },
		{ name: "dessert" },
		{ name: "suppe" },
	]);
	console.log(`Created ${categories.length} categories`);
	
	const catMap = {};
	categories.forEach((c) => {
		catMap[c.name] = c._id;
	});
	
	const recipes = await Recipe.insertMany([
		{
			name: "Spaghetti Bolognese",
			ingredients: [
				{ ingredient: "Spaghetti", amount: 400, unit: "g" },
				{ ingredient: "Hackfleisch", amount: 500, unit: "g" },
				{ ingredient: "Tomatensoße", amount: 500, unit: "ml" },
				{ ingredient: "Zwiebel", amount: 2, unit: "Stück" },
				{ ingredient: "Knoblauch", amount: 3, unit: "Zehen" },
				{ ingredient: "Olivenöl", amount: 2, unit: "EL" },
			],
			portion: 4,
			nutritionalValues: [{ kcal: "520", protein: "28g", fat: "18g", carbohydrates: "62g" }],
			directions: "Zwiebeln und Knoblauch fein hacken und in Olivenöl anbraten. Hackfleisch hinzufügen und krümelig braten. Tomatensoße dazugeben und 20 Minuten köcheln lassen. Spaghetti nach Packungsanweisung kochen und mit der Soße servieren.",
			tags: ["pasta", "italienisch", "klassiker"],
			href: "https://img.chefkoch-cdn.de/rezepte/393031127655461/bilder/1618353/crop-640x427/spaghetti-bolognese.jpg",
			time: 35,
			comments: [],
			rating: [4, 5, 4, 5],
			categories: [catMap["fleisch"]],
			user: user1._id,
		},
		{
			name: "Gemüse-Curry",
			ingredients: [
				{ ingredient: "Kartoffeln", amount: 300, unit: "g" },
				{ ingredient: "Kichererbsen", amount: 400, unit: "g" },
				{ ingredient: "Kokosmilch", amount: 400, unit: "ml" },
				{ ingredient: "Currypaste", amount: 3, unit: "EL" },
				{ ingredient: "Spinat", amount: 200, unit: "g" },
				{ ingredient: "Reis", amount: 300, unit: "g" },
			],
			portion: 4,
			nutritionalValues: [{ kcal: "450", protein: "14g", fat: "22g", carbohydrates: "48g" }],
			directions: "Kartoffeln schälen und würfeln. Currypaste in einem Topf anrösten, Kokosmilch und Kartoffeln dazugeben. 15 Minuten kochen. Kichererbsen und Spinat einrühren und weitere 5 Minuten garen. Mit Reis servieren.",
			tags: ["curry", "asiatisch", "gesund"],
			href: "https://www.familienkost.de/images/gemuesecurry.jpg",
			time: 30,
			comments: [],
			rating: [5, 4, 5],
			categories: [catMap["vegan"]],
			user: user1._id,
		},
		{
			name: "Caesar Salad",
			ingredients: [
				{ ingredient: "Römersalat", amount: 2, unit: "Stück" },
				{ ingredient: "Parmesan", amount: 80, unit: "g" },
				{ ingredient: "Croutons", amount: 100, unit: "g" },
				{ ingredient: "Hähnchenbrust", amount: 300, unit: "g" },
				{ ingredient: "Caesar-Dressing", amount: 100, unit: "ml" },
			],
			portion: 2,
			nutritionalValues: [{ kcal: "380", protein: "32g", fat: "20g", carbohydrates: "18g" }],
			directions: "Hähnchenbrust anbraten und in Streifen schneiden. Römersalat waschen und zerteilen. Salat mit Dressing mischen, Hähnchen, Parmesan und Croutons darüber geben.",
			tags: ["salat", "leicht", "klassiker"],
			href: "https://img.chefkoch-cdn.de/rezepte/956701201250684/bilder/1616492/crop-640x427/caesar-salad.jpg",
			time: 20,
			comments: [],
			rating: [4, 3, 5, 4],
			categories: [catMap["fleisch"]],
			user: user1._id,
		},
		{
			name: "Tomatensuppe",
			ingredients: [
				{ ingredient: "Tomaten", amount: 800, unit: "g" },
				{ ingredient: "Zwiebel", amount: 1, unit: "Stück" },
				{ ingredient: "Knoblauch", amount: 2, unit: "Zehen" },
				{ ingredient: "Gemüsebrühe", amount: 500, unit: "ml" },
				{ ingredient: "Sahne", amount: 100, unit: "ml" },
				{ ingredient: "Basilikum", amount: 1, unit: "Bund" },
			],
			portion: 4,
			nutritionalValues: [{ kcal: "180", protein: "4g", fat: "10g", carbohydrates: "18g" }],
			directions: "Zwiebel und Knoblauch anbraten. Tomaten dazugeben und mit Brühe aufgießen. 20 Minuten kochen und pürieren. Sahne einrühren und mit Basilikum garnieren.",
			tags: ["suppe", "einfach", "schnell"],
			href: "https://img.chefkoch-cdn.de/rezepte/1373751242290581/bilder/1499747/crop-960x540/frische-tomatensuppe.jpg",
			time: 30,
			comments: [],
			rating: [5, 5, 4],
			categories: [catMap["vegetarisch"], catMap["suppe"]],
			user: user1._id,
		},
		{
			name: "Lachs mit Spargel",
			ingredients: [
				{ ingredient: "Lachsfilet", amount: 400, unit: "g" },
				{ ingredient: "Spargel", amount: 500, unit: "g" },
				{ ingredient: "Zitrone", amount: 1, unit: "Stück" },
				{ ingredient: "Butter", amount: 30, unit: "g" },
				{ ingredient: "Dill", amount: 1, unit: "Bund" },
			],
			portion: 2,
			nutritionalValues: [{ kcal: "420", protein: "38g", fat: "24g", carbohydrates: "8g" }],
			directions: "Spargel schälen und in Salzwasser 12 Minuten kochen. Lachsfilet salzen, pfeffern und in Butter von jeder Seite 4 Minuten braten. Mit Zitrone und Dill servieren.",
			tags: ["fisch", "gesund", "frühling"],
			href: "https://image.essen-und-trinken.de/13790630/t/jO/v2/w960/r1/-/spargel-mit-lachs.jpg",
			time: 25,
			comments: [],
			rating: [5, 4, 5, 5],
			categories: [catMap["fisch"]],
			user: user1._id,
		},
		{
			name: "Schokoladenkuchen",
			ingredients: [
				{ ingredient: "Zartbitterschokolade", amount: 200, unit: "g" },
				{ ingredient: "Butter", amount: 150, unit: "g" },
				{ ingredient: "Zucker", amount: 150, unit: "g" },
				{ ingredient: "Eier", amount: 4, unit: "Stück" },
				{ ingredient: "Mehl", amount: 100, unit: "g" },
				{ ingredient: "Backpulver", amount: 1, unit: "TL" },
			],
			portion: 8,
			nutritionalValues: [{ kcal: "380", protein: "6g", fat: "22g", carbohydrates: "40g" }],
			directions: "Schokolade und Butter im Wasserbad schmelzen. Eier und Zucker schaumig schlagen. Schokoladenmischung unterrühren. Mehl und Backpulver unterheben. Bei 180°C 25 Minuten backen.",
			tags: ["backen", "schokolade", "kuchen"],
			href: "https://recipesblob.azureedge.net/assets/d7eb11d0eb3b42e1a5a33d3c693e3326/1920x1153/schokoladenkuchen_qf_2638.jpg",
			time: 45,
			comments: [],
			rating: [5, 5, 5, 4, 5],
			categories: [catMap["dessert"], catMap["vegetarisch"]],
			user: user2._id,
		},
		{
			name: "Pad Thai",
			ingredients: [
				{ ingredient: "Reisnudeln", amount: 250, unit: "g" },
				{ ingredient: "Garnelen", amount: 200, unit: "g" },
				{ ingredient: "Ei", amount: 2, unit: "Stück" },
				{ ingredient: "Sojasoße", amount: 3, unit: "EL" },
				{ ingredient: "Limette", amount: 1, unit: "Stück" },
				{ ingredient: "Erdnüsse", amount: 50, unit: "g" },
			],
			portion: 2,
			nutritionalValues: [{ kcal: "480", protein: "26g", fat: "14g", carbohydrates: "64g" }],
			directions: "Reisnudeln nach Packungsanweisung einweichen. Garnelen anbraten, Ei dazugeben und verrühren. Nudeln und Sojasoße hinzufügen, alles zusammen schwenken. Mit Limette und gehackten Erdnüssen servieren.",
			tags: ["asiatisch", "nudeln", "garnelen"],
			href: "https://c.rewe-static.de/50111814/1/50111814.png?impolicy=rds&im=Resize,width=1480",
			time: 20,
			comments: [],
			rating: [5, 4, 4],
			categories: [catMap["fisch"]],
			user: user2._id,
		},
		{
			name: "Kartoffelgratin",
			ingredients: [
				{ ingredient: "Kartoffeln", amount: 1000, unit: "g" },
				{ ingredient: "Sahne", amount: 300, unit: "ml" },
				{ ingredient: "Gruyère", amount: 150, unit: "g" },
				{ ingredient: "Knoblauch", amount: 2, unit: "Zehen" },
				{ ingredient: "Muskatnuss", amount: 1, unit: "Prise" },
			],
			portion: 6,
			nutritionalValues: [{ kcal: "350", protein: "12g", fat: "20g", carbohydrates: "30g" }],
			directions: "Kartoffeln schälen und in dünne Scheiben schneiden. Auflaufform mit Knoblauch einreiben. Kartoffeln schichten, Sahne mit Muskat würzen und darüber gießen. Käse darüber streuen. Bei 180°C 45 Minuten backen.",
			tags: ["gratin", "kartoffel", "überbacken"],
			href: "https://fitaliancook.com/wp-content/uploads/2022/07/kartoffelgratin-rezept-einfach-beitragsbild.jpg",
			time: 60,
			comments: [],
			rating: [4, 5, 5],
			categories: [catMap["vegetarisch"]],
			user: user2._id,
		},
		{
			name: "Griechischer Salat",
			ingredients: [
				{ ingredient: "Gurke", amount: 1, unit: "Stück" },
				{ ingredient: "Tomaten", amount: 4, unit: "Stück" },
				{ ingredient: "Feta", amount: 200, unit: "g" },
				{ ingredient: "Oliven", amount: 100, unit: "g" },
				{ ingredient: "Rote Zwiebel", amount: 1, unit: "Stück" },
				{ ingredient: "Olivenöl", amount: 4, unit: "EL" },
			],
			portion: 2,
			nutritionalValues: [{ kcal: "320", protein: "14g", fat: "26g", carbohydrates: "10g" }],
			directions: "Gurke, Tomaten und Zwiebel in Stücke schneiden. Oliven dazugeben. Feta darüber bröseln. Mit Olivenöl, Salz und Oregano würzen.",
			tags: ["salat", "griechisch", "sommer"],
			href: "https://emmikochteinfach.de/wp-content/uploads/2018/06/Griechischer-Bauernsalat-3.jpg",
			time: 10,
			comments: [],
			rating: [4, 4, 5, 3],
			categories: [catMap["vegetarisch"]],
			user: user2._id,
		},
		{
			name: "Rindergulasch",
			ingredients: [
				{ ingredient: "Rindfleisch", amount: 800, unit: "g" },
				{ ingredient: "Zwiebeln", amount: 4, unit: "Stück" },
				{ ingredient: "Paprikapulver", amount: 3, unit: "EL" },
				{ ingredient: "Tomatenmark", amount: 2, unit: "EL" },
				{ ingredient: "Rinderbrühe", amount: 500, unit: "ml" },
				{ ingredient: "Kartoffeln", amount: 500, unit: "g" },
			],
			portion: 4,
			nutritionalValues: [{ kcal: "580", protein: "42g", fat: "22g", carbohydrates: "48g" }],
			directions: "Rindfleisch in Würfel schneiden und scharf anbraten. Zwiebeln dazugeben und glasig dünsten. Paprikapulver und Tomatenmark einrühren. Mit Brühe ablöschen und 90 Minuten schmoren. Kartoffeln die letzten 30 Minuten mitkochen.",
			tags: ["eintopf", "deftig", "winter"],
			href: "https://emmikochteinfach.de/wp-content/uploads/2022/02/seo_Gulasch-Nah-200.jpg",
			time: 120,
			comments: [],
			rating: [5, 5, 4, 5],
			categories: [catMap["fleisch"], catMap["suppe"]],
			user: user2._id,
		},
		{
			name: "Panna Cotta",
			ingredients: [
				{ ingredient: "Sahne", amount: 500, unit: "ml" },
				{ ingredient: "Zucker", amount: 80, unit: "g" },
				{ ingredient: "Vanilleschote", amount: 1, unit: "Stück" },
				{ ingredient: "Gelatine", amount: 3, unit: "Blatt" },
				{ ingredient: "Erdbeeren", amount: 200, unit: "g" },
			],
			portion: 4,
			nutritionalValues: [{ kcal: "340", protein: "4g", fat: "28g", carbohydrates: "20g" }],
			directions: "Gelatine in kaltem Wasser einweichen. Sahne mit Zucker und Vanille aufkochen. Gelatine ausdrücken und einrühren. In Förmchen füllen und mindestens 4 Stunden kalt stellen. Mit Erdbeeren servieren.",
			tags: ["dessert", "italienisch", "nachtisch"],
			href: "https://www.gaumenfreundin.de/wp-content/uploads/2023/11/Panna-Cotta-Gaumenfreundin.jpg",
			time: 20,
			comments: [],
			rating: [5, 5, 4],
			categories: [catMap["dessert"], catMap["vegetarisch"]],
			user: user2._id,
		},
		{
			name: "Hähnchen-Wrap",
			ingredients: [
				{ ingredient: "Tortilla-Wraps", amount: 4, unit: "Stück" },
				{ ingredient: "Hähnchenbrust", amount: 400, unit: "g" },
				{ ingredient: "Eisbergsalat", amount: 100, unit: "g" },
				{ ingredient: "Tomate", amount: 2, unit: "Stück" },
				{ ingredient: "Joghurt-Dressing", amount: 100, unit: "ml" },
				{ ingredient: "Paprika", amount: 1, unit: "Stück" },
			],
			portion: 4,
			nutritionalValues: [{ kcal: "390", protein: "30g", fat: "12g", carbohydrates: "40g" }],
			directions: "Hähnchenbrust würzen und in Streifen braten. Gemüse klein schneiden. Wraps mit Dressing bestreichen, Salat, Gemüse und Hähnchen darauf verteilen und einrollen.",
			tags: ["wrap", "schnell", "mittagessen"],
			href: "https://cdn.vilgain.com/image/recipe-cover/cover-desktop/f6846e9b-4291-452d-ba3f-229bd92be2b2?v=1709925470",
			time: 15,
			comments: [],
			rating: [4, 4, 3, 5],
			categories: [catMap["fleisch"]],
			user: user2._id,
		},
		{
			name: "Kürbissuppe",
			ingredients: [
				{ ingredient: "Hokkaido-Kürbis", amount: 1000, unit: "g" },
				{ ingredient: "Zwiebel", amount: 1, unit: "Stück" },
				{ ingredient: "Ingwer", amount: 20, unit: "g" },
				{ ingredient: "Kokosmilch", amount: 200, unit: "ml" },
				{ ingredient: "Gemüsebrühe", amount: 500, unit: "ml" },
				{ ingredient: "Kürbiskerne", amount: 30, unit: "g" },
			],
			portion: 4,
			nutritionalValues: [{ kcal: "220", protein: "5g", fat: "12g", carbohydrates: "24g" }],
			directions: "Kürbis entkernen und würfeln. Zwiebel und Ingwer anbraten, Kürbis dazugeben. Mit Brühe aufgießen und 20 Minuten kochen. Pürieren, Kokosmilch einrühren. Mit Kürbiskernen garnieren.",
			tags: ["suppe", "herbst", "kürbis"],
			href: "https://d2sj0xby2hzqoy.cloudfront.net/kenwood_germany/attachments/data/000/021/915/medium/IMG_Querformat.jpg?1731573158",
			time: 35,
			comments: [],
			rating: [5, 4, 5, 5],
			categories: [catMap["vegan"], catMap["suppe"]],
			user: user2._id,
		},
		{
			name: "Wiener Schnitzel",
			ingredients: [
				{ ingredient: "Kalbsschnitzel", amount: 4, unit: "Stück" },
				{ ingredient: "Mehl", amount: 100, unit: "g" },
				{ ingredient: "Eier", amount: 3, unit: "Stück" },
				{ ingredient: "Semmelbrösel", amount: 200, unit: "g" },
				{ ingredient: "Butterschmalz", amount: 150, unit: "g" },
				{ ingredient: "Zitrone", amount: 1, unit: "Stück" },
			],
			portion: 4,
			nutritionalValues: [{ kcal: "520", protein: "34g", fat: "28g", carbohydrates: "32g" }],
			directions: "Schnitzel dünn klopfen, salzen. Nacheinander in Mehl, verquirltem Ei und Semmelbröseln wenden. In reichlich Butterschmalz goldbraun ausbacken. Mit Zitrone servieren.",
			tags: ["österreichisch", "klassiker", "paniert"],
			href: "https://images.services.kitchenstories.io/1nax_96ySr3E5VQMdkpNYCIln_c=/3840x0/filters:quality(80)/images.kitchenstories.io/wagtailOriginalImages/R3266_das_beste_wiener_schnitzel.jpg",
			time: 30,
			comments: [],
			rating: [5, 5, 5, 4, 5],
			categories: [catMap["fleisch"]],
			user: user2._id,
		},
		{
			name: "Ratatouille",
			ingredients: [
				{ ingredient: "Zucchini", amount: 2, unit: "Stück" },
				{ ingredient: "Aubergine", amount: 1, unit: "Stück" },
				{ ingredient: "Paprika", amount: 2, unit: "Stück" },
				{ ingredient: "Tomaten", amount: 400, unit: "g" },
				{ ingredient: "Knoblauch", amount: 3, unit: "Zehen" },
				{ ingredient: "Kräuter der Provence", amount: 2, unit: "TL" },
			],
			portion: 4,
			nutritionalValues: [{ kcal: "150", protein: "4g", fat: "6g", carbohydrates: "18g" }],
			directions: "Gemüse in Scheiben schneiden. In einer Auflaufform abwechselnd schichten. Mit Knoblauch, Kräutern und Olivenöl würzen. Bei 180°C 40 Minuten im Ofen garen.",
			tags: ["französisch", "gemüse", "ofen"],
			href: "https://www.kikkoman.de/fileadmin/_processed_/1/8/csm_1075-recipe-page-Saffron-scented-Ratatouille_desktop_5ddfe5fdbf.jpg",
			time: 55,
			comments: [],
			rating: [4, 5, 4],
			categories: [catMap["vegan"]],
			user: user2._id,
		},
		{
			name: "Fish and Chips",
			ingredients: [
				{ ingredient: "Kabeljaufilet", amount: 600, unit: "g" },
				{ ingredient: "Mehl", amount: 200, unit: "g" },
				{ ingredient: "Bier", amount: 250, unit: "ml" },
				{ ingredient: "Kartoffeln", amount: 800, unit: "g" },
				{ ingredient: "Öl zum Frittieren", amount: 1, unit: "l" },
				{ ingredient: "Erbsen", amount: 200, unit: "g" },
			],
			portion: 4,
			nutritionalValues: [{ kcal: "620", protein: "32g", fat: "28g", carbohydrates: "58g" }],
			directions: "Kartoffeln in Stifte schneiden und frittieren. Mehl mit Bier zu einem Teig verrühren. Fisch in Teig tauchen und goldbraun frittieren. Mit Erbsen servieren.",
			tags: ["britisch", "frittiert", "fisch"],
			href: "https://image.deutschesee.de/public/media/67/81/07/1762442770/Rezept-Fish-Chips-Thomas-Grill-2.jpg?ts=1762442770",
			time: 40,
			comments: [],
			rating: [4, 3, 4, 5],
			categories: [catMap["fisch"]],
			user: user2._id,
		},
		{
			name: "Risotto mit Pilzen",
			ingredients: [
				{ ingredient: "Risottoreis", amount: 300, unit: "g" },
				{ ingredient: "Champignons", amount: 300, unit: "g" },
				{ ingredient: "Gemüsebrühe", amount: 800, unit: "ml" },
				{ ingredient: "Weißwein", amount: 100, unit: "ml" },
				{ ingredient: "Parmesan", amount: 80, unit: "g" },
				{ ingredient: "Butter", amount: 40, unit: "g" },
			],
			portion: 4,
			nutritionalValues: [{ kcal: "420", protein: "14g", fat: "16g", carbohydrates: "52g" }],
			directions: "Pilze in Scheiben schneiden und anbraten. Reis dazugeben und mit Wein ablöschen. Nach und nach Brühe zugeben und unter Rühren garen. Zum Schluss Parmesan und Butter einrühren.",
			tags: ["risotto", "italienisch", "pilze"],
			href: "https://cdn.reishunger.com/pilz-risotto-mit-kraeutern.jpg?width=989&height=659&quality=85&aspect_ratio=989%3A659",
			time: 35,
			comments: [],
			rating: [5, 4, 5, 4],
			categories: [catMap["vegetarisch"]],
			user: user2._id,
		},
		{
			name: "Tacos mit Hackfleisch",
			ingredients: [
				{ ingredient: "Taco-Shells", amount: 12, unit: "Stück" },
				{ ingredient: "Hackfleisch", amount: 500, unit: "g" },
				{ ingredient: "Kidneybohnen", amount: 250, unit: "g" },
				{ ingredient: "Eisbergsalat", amount: 100, unit: "g" },
				{ ingredient: "Cheddar", amount: 100, unit: "g" },
				{ ingredient: "Salsa", amount: 200, unit: "ml" },
			],
			portion: 4,
			nutritionalValues: [{ kcal: "490", protein: "28g", fat: "22g", carbohydrates: "46g" }],
			directions: "Hackfleisch anbraten und mit Gewürzen abschmecken. Kidneybohnen dazugeben. Taco-Shells im Ofen erwärmen. Mit Hackfleisch, Salat, Käse und Salsa füllen.",
			tags: ["mexikanisch", "tacos", "party"],
			href: "https://www.gaumenfreundin.de/wp-content/uploads/2023/04/Tacos-von-Gaumenfreundin.jpg",
			time: 25,
			comments: [],
			rating: [5, 4, 5],
			categories: [catMap["fleisch"]],
			user: user2._id,
		},
		{
			name: "Linsensuppe",
			ingredients: [
				{ ingredient: "Rote Linsen", amount: 300, unit: "g" },
				{ ingredient: "Karotten", amount: 2, unit: "Stück" },
				{ ingredient: "Zwiebel", amount: 1, unit: "Stück" },
				{ ingredient: "Kreuzkümmel", amount: 1, unit: "TL" },
				{ ingredient: "Gemüsebrühe", amount: 800, unit: "ml" },
				{ ingredient: "Zitronensaft", amount: 2, unit: "EL" },
			],
			portion: 4,
			nutritionalValues: [{ kcal: "280", protein: "18g", fat: "3g", carbohydrates: "44g" }],
			directions: "Zwiebel und Karotten würfeln und anbraten. Kreuzkümmel dazugeben. Linsen und Brühe hinzufügen. 20 Minuten kochen und pürieren. Mit Zitronensaft abschmecken.",
			tags: ["suppe", "linsen", "proteinreich"],
			href: "https://www.justspices.de/media/recipe/8FAEEAC9-9470-4825-B1B3-3486F0F29EC4_1_201_a.jpeg",
			time: 30,
			comments: [],
			rating: [4, 5, 4, 4],
			categories: [catMap["vegan"], catMap["suppe"]],
			user: user2._id,
		},
		{
			name: "Tiramisu",
			ingredients: [
				{ ingredient: "Mascarpone", amount: 500, unit: "g" },
				{ ingredient: "Eier", amount: 4, unit: "Stück" },
				{ ingredient: "Zucker", amount: 100, unit: "g" },
				{ ingredient: "Löffelbiskuit", amount: 200, unit: "g" },
				{ ingredient: "Espresso", amount: 300, unit: "ml" },
				{ ingredient: "Kakaopulver", amount: 20, unit: "g" },
			],
			portion: 6,
			nutritionalValues: [{ kcal: "420", protein: "10g", fat: "28g", carbohydrates: "34g" }],
			directions: "Eigelb mit Zucker schaumig schlagen. Mascarpone unterrühren. Eiweiß steif schlagen und unterheben. Löffelbiskuit in Espresso tauchen und schichten. Mit Mascarponecreme bedecken. Mindestens 4 Stunden kühlen. Mit Kakao bestäuben.",
			tags: ["dessert", "italienisch", "kaffee"],
			href: "https://img.chefkoch-cdn.de/rezepte/264171102553424/bilder/1618363/crop-960x540/tiramisu.jpg",
			time: 30,
			comments: [],
			rating: [5, 5, 5, 5],
			categories: [catMap["dessert"], catMap["vegetarisch"]],
			user: user2._id,
		},
		{
			name: "Gulaschsuppe",
			ingredients: [
				{ ingredient: "Rindfleisch", amount: 500, unit: "g" },
				{ ingredient: "Kartoffeln", amount: 400, unit: "g" },
				{ ingredient: "Paprika", amount: 3, unit: "Stück" },
				{ ingredient: "Zwiebeln", amount: 2, unit: "Stück" },
				{ ingredient: "Paprikapulver", amount: 3, unit: "EL" },
				{ ingredient: "Rinderbrühe", amount: 1000, unit: "ml" },
			],
			portion: 6,
			nutritionalValues: [{ kcal: "380", protein: "28g", fat: "14g", carbohydrates: "32g" }],
			directions: "Fleisch in Würfel schneiden und anbraten. Zwiebeln und Paprika dazugeben. Mit Paprikapulver bestäuben und Brühe angießen. 60 Minuten köcheln. Kartoffeln die letzten 20 Minuten mitkochen.",
			tags: ["suppe", "ungarisch", "deftig"],
			href: "https://www.familienkost.de/images/gulaschsuppe.jpg",
			time: 90,
			comments: [],
			rating: [5, 4, 4, 5],
			categories: [catMap["fleisch"], catMap["suppe"]],
			user: user2._id,
		},
		{
			name: "Banana Bread",
			ingredients: [
				{ ingredient: "Reife Bananen", amount: 3, unit: "Stück" },
				{ ingredient: "Mehl", amount: 280, unit: "g" },
				{ ingredient: "Zucker", amount: 100, unit: "g" },
				{ ingredient: "Butter", amount: 80, unit: "g" },
				{ ingredient: "Ei", amount: 1, unit: "Stück" },
				{ ingredient: "Backpulver", amount: 1, unit: "TL" },
			],
			portion: 8,
			nutritionalValues: [{ kcal: "290", protein: "4g", fat: "10g", carbohydrates: "46g" }],
			directions: "Bananen zerdrücken. Butter schmelzen und mit Zucker und Ei verrühren. Mehl und Backpulver unterheben. Bananen einrühren. In eine Kastenform füllen und bei 175°C 55 Minuten backen.",
			tags: ["backen", "banane", "frühstück"],
			href: "https://www.allrecipes.com/thmb/fAkQn-FhjF89oTJ5JXpgwvwNf34=/1500x0/filters:no_upscale():max_bytes(150000):strip_icc()/20144-banana-banana-bread-VAT-009-4x3-B-78f1cfc64bfa451e8a0fead814719b9f.jpg",
			time: 65,
			comments: [],
			rating: [5, 4, 5, 4],
			categories: [catMap["dessert"], catMap["vegetarisch"]],
			user: user2._id,
		},
		{
			name: "Bruschetta",
			ingredients: [
				{ ingredient: "Ciabatta", amount: 1, unit: "Stück" },
				{ ingredient: "Tomaten", amount: 6, unit: "Stück" },
				{ ingredient: "Knoblauch", amount: 2, unit: "Zehen" },
				{ ingredient: "Basilikum", amount: 1, unit: "Bund" },
				{ ingredient: "Olivenöl", amount: 4, unit: "EL" },
				{ ingredient: "Balsamico", amount: 1, unit: "EL" },
			],
			portion: 4,
			nutritionalValues: [{ kcal: "220", protein: "6g", fat: "10g", carbohydrates: "28g" }],
			directions: "Brot in Scheiben schneiden und toasten. Tomaten würfeln, mit Knoblauch, Basilikum, Öl und Balsamico mischen. Auf die getoasteten Brotscheiben geben.",
			tags: ["vorspeise", "italienisch", "schnell"],
			href: "https://www.hammermuehle-shop.de/media/2c/1f/6e/1747389463/Rezept_Bruschetta_3.jpg?ts=1755180332",
			time: 15,
			comments: [],
			rating: [4, 5, 4],
			categories: [catMap["vegan"]],
			user: user2._id,
		},
		{
			name: "Chicken Tikka Masala",
			ingredients: [
				{ ingredient: "Hähnchenbrust", amount: 600, unit: "g" },
				{ ingredient: "Joghurt", amount: 150, unit: "g" },
				{ ingredient: "Tomatensoße", amount: 400, unit: "ml" },
				{ ingredient: "Sahne", amount: 100, unit: "ml" },
				{ ingredient: "Garam Masala", amount: 2, unit: "EL" },
				{ ingredient: "Basmati-Reis", amount: 300, unit: "g" },
			],
			portion: 4,
			nutritionalValues: [{ kcal: "520", protein: "38g", fat: "18g", carbohydrates: "50g" }],
			directions: "Hähnchen in Joghurt und Gewürzen marinieren. Anbraten und Tomatensoße dazugeben. 20 Minuten köcheln lassen. Sahne einrühren. Mit Basmati-Reis servieren.",
			tags: ["indisch", "curry", "hähnchen"],
			href: "https://www.gaumenfreundin.de/wp-content/uploads/2025/01/Chicken-Tikka-Masala-einfaches-Rezept.jpg",
			time: 40,
			comments: [],
			rating: [5, 5, 4, 5],
			categories: [catMap["fleisch"]],
			user: user2._id,
		},
		{
			name: "Schweinebraten",
			ingredients: [
				{ ingredient: "Schweinenacken", amount: 1200, unit: "g" },
				{ ingredient: "Zwiebeln", amount: 3, unit: "Stück" },
				{ ingredient: "Dunkelbier", amount: 500, unit: "ml" },
				{ ingredient: "Kümmel", amount: 1, unit: "TL" },
				{ ingredient: "Semmelknödel", amount: 6, unit: "Stück" },
				{ ingredient: "Sauerkraut", amount: 400, unit: "g" },
			],
			portion: 6,
			nutritionalValues: [{ kcal: "620", protein: "40g", fat: "30g", carbohydrates: "42g" }],
			directions: "Schwarte rautenförmig einschneiden. Fleisch salzen und mit Kümmel würzen. Mit Zwiebeln in den Bräter geben und mit Bier angießen. Bei 160°C 2,5 Stunden im Ofen schmoren. Mit Knödeln und Sauerkraut servieren.",
			tags: ["bayerisch", "braten", "sonntagsessen"],
			href: "https://img.chefkoch-cdn.de/rezepte/2063791333612329/bilder/1424408/crop-960x540/schweinebraten-resche-kruste-leckere-sosse.jpg",
			time: 180,
			comments: [],
			rating: [5, 5, 5, 5, 4],
			categories: [catMap["fleisch"]],
			user: user2._id,
		},
		{
			name: "Falafel mit Hummus",
			ingredients: [
				{ ingredient: "Kichererbsen", amount: 400, unit: "g" },
				{ ingredient: "Petersilie", amount: 1, unit: "Bund" },
				{ ingredient: "Kreuzkümmel", amount: 2, unit: "TL" },
				{ ingredient: "Knoblauch", amount: 3, unit: "Zehen" },
				{ ingredient: "Tahini", amount: 3, unit: "EL" },
				{ ingredient: "Fladenbrot", amount: 4, unit: "Stück" },
			],
			portion: 4,
			nutritionalValues: [{ kcal: "380", protein: "16g", fat: "14g", carbohydrates: "48g" }],
			directions: "Kichererbsen mit Petersilie, Knoblauch und Kreuzkümmel im Mixer zerkleinern. Kleine Bällchen formen und in Öl goldbraun frittieren. Für den Hummus restliche Kichererbsen mit Tahini und Zitrone pürieren. Mit Fladenbrot servieren.",
			tags: ["orientalisch", "falafel", "streetfood"],
			href: "https://www.daskochrezept.de/sites/daskochrezept.de/files/styles/full_width_tablet_4_3/public/2021-06/hummus_falafel_1.jpg?h=10d202d3&itok=GzhdWPZw",
			time: 40,
			comments: [],
			rating: [5, 4, 5, 4],
			categories: [catMap["vegan"]],
			user: user2._id,
		},
		{
			name: "Omelett mit Kräutern",
			ingredients: [
				{ ingredient: "Eier", amount: 3, unit: "Stück" },
				{ ingredient: "Milch", amount: 30, unit: "ml" },
				{ ingredient: "Schnittlauch", amount: 1, unit: "Bund" },
				{ ingredient: "Petersilie", amount: 1, unit: "Bund" },
				{ ingredient: "Butter", amount: 15, unit: "g" },
				{ ingredient: "Käse", amount: 50, unit: "g" },
			],
			portion: 1,
			nutritionalValues: [{ kcal: "350", protein: "22g", fat: "26g", carbohydrates: "4g" }],
			directions: "Eier mit Milch verquirlen. Kräuter fein hacken und untermischen. Butter in der Pfanne erhitzen, Eimasse hineingeben. Bei mittlerer Hitze stocken lassen, Käse darüber streuen und zusammenklappen.",
			tags: ["frühstück", "eier", "schnell"],
			href: "https://image.brigitte.de/10940148/t/9o/v4/w1440/r1.5/-/kraeuter-omelette.jpg",
			time: 10,
			comments: [],
			rating: [4, 4, 5],
			categories: [catMap["vegetarisch"]],
			user: user2._id,
		},
		{
			name: "Sushi-Bowl",
			ingredients: [
				{ ingredient: "Sushi-Reis", amount: 300, unit: "g" },
				{ ingredient: "Lachs (Sashimi)", amount: 300, unit: "g" },
				{ ingredient: "Avocado", amount: 1, unit: "Stück" },
				{ ingredient: "Gurke", amount: 1, unit: "Stück" },
				{ ingredient: "Sojasoße", amount: 3, unit: "EL" },
				{ ingredient: "Sesam", amount: 2, unit: "EL" },
			],
			portion: 2,
			nutritionalValues: [{ kcal: "520", protein: "30g", fat: "18g", carbohydrates: "60g" }],
			directions: "Sushi-Reis kochen und mit Reisessig würzen. Lachs in Würfel schneiden. Avocado und Gurke in Scheiben schneiden. Reis in Schüsseln anrichten und mit Lachs, Avocado, Gurke, Sojasoße und Sesam toppen.",
			tags: ["japanisch", "sushi", "bowl"],
			href: "https://images.lecker.de/sushi-bowl,id=66ead5a1,b=lecker,w=1600,rm=sk.jpeg",
			time: 25,
			comments: [],
			rating: [5, 5, 4, 5],
			categories: [catMap["fisch"]],
			user: user2._id,
		},
		{
			name: "Apfelstrudel",
			ingredients: [
				{ ingredient: "Äpfel", amount: 1000, unit: "g" },
				{ ingredient: "Strudelteig", amount: 1, unit: "Packung" },
				{ ingredient: "Zucker", amount: 80, unit: "g" },
				{ ingredient: "Zimt", amount: 2, unit: "TL" },
				{ ingredient: "Rosinen", amount: 50, unit: "g" },
				{ ingredient: "Butter", amount: 60, unit: "g" },
			],
			portion: 6,
			nutritionalValues: [{ kcal: "310", protein: "3g", fat: "12g", carbohydrates: "48g" }],
			directions: "Äpfel schälen und in dünne Scheiben schneiden. Mit Zucker, Zimt und Rosinen mischen. Strudelteig ausbreiten und mit Butter bepinseln. Füllung darauf verteilen und aufrollen. Bei 180°C 35 Minuten goldbraun backen.",
			tags: ["österreichisch", "backen", "apfel"],
			href: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQJR1j4b-y2vAXRCk9BOjhrItJVGh5Z1H9APA&s",
			time: 50,
			comments: [],
			rating: [5, 5, 4, 5],
			categories: [catMap["dessert"], catMap["vegetarisch"]],
			user: user2._id,
		},
		{
			name: "Pulled Pork Burger",
			ingredients: [
				{ ingredient: "Schweinenacken", amount: 1500, unit: "g" },
				{ ingredient: "BBQ-Soße", amount: 200, unit: "ml" },
				{ ingredient: "Burgerbrötchen", amount: 6, unit: "Stück" },
				{ ingredient: "Krautsalat", amount: 200, unit: "g" },
				{ ingredient: "Paprikapulver", amount: 2, unit: "EL" },
				{ ingredient: "Brauner Zucker", amount: 2, unit: "EL" },
			],
			portion: 6,
			nutritionalValues: [{ kcal: "580", protein: "36g", fat: "24g", carbohydrates: "50g" }],
			directions: "Schweinenacken mit Gewürzen einreiben. Bei 130°C 5 Stunden im Ofen garen. Fleisch mit Gabeln zerteilen und mit BBQ-Soße mischen. Auf Brötchen mit Krautsalat servieren.",
			tags: ["burger", "bbq", "amerikanisch"],
			href: "https://assets.tmecosys.com/image/upload/t_web_rdp_recipe_584x480_1_5x/img/recipe/ras/Assets/FE8C808F-2B44-41A7-83FE-1104B03D81A1/Derivates/84099AAC-1D87-4738-8AEF-7C836EC4E32A.jpg",
			time: 320,
			comments: [],
			rating: [5, 5, 5, 4, 5],
			categories: [catMap["fleisch"]],
			user: user2._id,
		},
		{
			name: "Quiche Lorraine",
			ingredients: [
				{ ingredient: "Mürbeteig", amount: 1, unit: "Rolle" },
				{ ingredient: "Speck", amount: 200, unit: "g" },
				{ ingredient: "Eier", amount: 3, unit: "Stück" },
				{ ingredient: "Sahne", amount: 200, unit: "ml" },
				{ ingredient: "Gruyère", amount: 100, unit: "g" },
				{ ingredient: "Muskatnuss", amount: 1, unit: "Prise" },
			],
			portion: 6,
			nutritionalValues: [{ kcal: "420", protein: "18g", fat: "30g", carbohydrates: "22g" }],
			directions: "Teig in eine Tarteform legen. Speck anbraten. Eier mit Sahne und Muskat verquirlen. Speck auf den Teig geben, Eimasse darüber gießen, Käse darüber streuen. Bei 180°C 35 Minuten backen.",
			tags: ["französisch", "quiche", "herzhaft"],
			href: "https://img.chefkoch-cdn.de/rezepte/2524041395748056/bilder/1619475/crop-960x540/quiche-lorraine-der-klassiker.jpg",
			time: 50,
			comments: [],
			rating: [4, 5, 4, 4],
			categories: [catMap["fleisch"]],
			user: user2._id,
		},
		{
			name: "Smoothie Bowl",
			ingredients: [
				{ ingredient: "Gefrorene Beeren", amount: 200, unit: "g" },
				{ ingredient: "Banane", amount: 1, unit: "Stück" },
				{ ingredient: "Hafermilch", amount: 100, unit: "ml" },
				{ ingredient: "Granola", amount: 50, unit: "g" },
				{ ingredient: "Chiasamen", amount: 1, unit: "EL" },
				{ ingredient: "Kokosflocken", amount: 10, unit: "g" },
			],
			portion: 1,
			nutritionalValues: [{ kcal: "350", protein: "8g", fat: "10g", carbohydrates: "58g" }],
			directions: "Gefrorene Beeren, Banane und Hafermilch im Mixer pürieren. In eine Schüssel geben. Mit Granola, Chiasamen und Kokosflocken toppen.",
			tags: ["frühstück", "gesund", "bowl"],
			href: "https://www.einfachbacken.de/sites/einfachbacken.de/files/styles/1946_1460/public/2019-08/smoothie_bowl_mit_beeren-1.jpg?h=4521fff0&itok=Y-9mNfgm",
			time: 5,
			comments: [],
			rating: [5, 4, 5],
			categories: [catMap["vegan"], catMap["dessert"]],
			user: user2._id,
		},
		{
			name: "Lasagne",
			ingredients: [
				{ ingredient: "Lasagneplatten", amount: 250, unit: "g" },
				{ ingredient: "Hackfleisch", amount: 500, unit: "g" },
				{ ingredient: "Tomatensoße", amount: 500, unit: "ml" },
				{ ingredient: "Béchamelsoße", amount: 400, unit: "ml" },
				{ ingredient: "Mozzarella", amount: 200, unit: "g" },
				{ ingredient: "Parmesan", amount: 50, unit: "g" },
			],
			portion: 6,
			nutritionalValues: [{ kcal: "520", protein: "30g", fat: "24g", carbohydrates: "44g" }],
			directions: "Hackfleisch anbraten und Tomatensoße einrühren. In einer Auflaufform abwechselnd Lasagneplatten, Fleischsoße und Béchamelsoße schichten. Mit Mozzarella und Parmesan bestreuen. Bei 180°C 40 Minuten backen.",
			tags: ["italienisch", "auflauf", "klassiker"],
			href: "https://img.chefkoch-cdn.de/rezepte/745721177147257/bilder/668335/crop-960x540/lasagne.jpg",
			time: 60,
			comments: [],
			rating: [5, 5, 4, 5, 5],
			categories: [catMap["fleisch"]],
			user: user2._id,
		},
		{
			name: "Gnocchi mit Salbei-Butter",
			ingredients: [
				{ ingredient: "Gnocchi", amount: 500, unit: "g" },
				{ ingredient: "Butter", amount: 80, unit: "g" },
				{ ingredient: "Salbeiblätter", amount: 15, unit: "Stück" },
				{ ingredient: "Parmesan", amount: 60, unit: "g" },
				{ ingredient: "Pinienkerne", amount: 30, unit: "g" },
			],
			portion: 2,
			nutritionalValues: [{ kcal: "560", protein: "16g", fat: "32g", carbohydrates: "52g" }],
			directions: "Gnocchi in Salzwasser kochen bis sie aufschwimmen. Butter in einer Pfanne bräunen. Salbeiblätter und Pinienkerne darin rösten. Gnocchi dazugeben und schwenken. Mit Parmesan servieren.",
			tags: ["italienisch", "gnocchi", "butter"],
			href: "https://www.kuechengoetter.de/uploads/media/1800x1200/01/49861-gnocchi-mit-salbeibutter.jpg?v=2-17",
			time: 15,
			comments: [],
			rating: [5, 5, 4],
			categories: [catMap["vegetarisch"]],
			user: user2._id,
		},
		{
			name: "Chili con Carne",
			ingredients: [
				{ ingredient: "Hackfleisch", amount: 500, unit: "g" },
				{ ingredient: "Kidneybohnen", amount: 400, unit: "g" },
				{ ingredient: "Mais", amount: 200, unit: "g" },
				{ ingredient: "Tomaten (gehackt)", amount: 400, unit: "g" },
				{ ingredient: "Chilipulver", amount: 2, unit: "TL" },
				{ ingredient: "Kreuzkümmel", amount: 1, unit: "TL" },
			],
			portion: 4,
			nutritionalValues: [{ kcal: "480", protein: "32g", fat: "20g", carbohydrates: "40g" }],
			directions: "Hackfleisch anbraten. Gewürze dazugeben und kurz mitrösten. Tomaten, Bohnen und Mais hinzufügen. 30 Minuten bei niedriger Hitze köcheln lassen. Mit Sauerrahm und Reis servieren.",
			tags: ["mexikanisch", "scharf", "eintopf"],
			href: "https://www.familienkost.de/images/chili-con-carne-rezept.jpg",
			time: 45,
			comments: [],
			rating: [4, 5, 4, 5, 4],
			categories: [catMap["fleisch"]],
			user: user2._id,
		},
		{
			name: "Crème Brûlée",
			ingredients: [
				{ ingredient: "Sahne", amount: 500, unit: "ml" },
				{ ingredient: "Eigelb", amount: 5, unit: "Stück" },
				{ ingredient: "Zucker", amount: 100, unit: "g" },
				{ ingredient: "Vanilleschote", amount: 1, unit: "Stück" },
			],
			portion: 4,
			nutritionalValues: [{ kcal: "380", protein: "6g", fat: "30g", carbohydrates: "22g" }],
			directions: "Sahne mit Vanille aufkochen. Eigelb mit 60g Zucker schaumig schlagen. Sahne langsam einrühren. In Förmchen füllen und bei 150°C 40 Minuten im Wasserbad garen. Abkühlen lassen, mit Zucker bestreuen und karamellisieren.",
			tags: ["französisch", "dessert", "elegant"],
			href: "https://www.allrecipes.com/thmb/y-S61IJkYyCUjTMGYqkaoJGwBrY=/1500x0/filters:no_upscale():max_bytes(150000):strip_icc()/AR-228515-simple-creme-brulee-dessert-dmfs-4x3-821623e7a86548eeb89370ac23d5f251.jpg",
			time: 60,
			comments: [],
			rating: [5, 5, 5, 5],
			categories: [catMap["dessert"], catMap["vegetarisch"]],
			user: user2._id,
		},
		{
			name: "Pho Bo",
			ingredients: [
				{ ingredient: "Rinderknochen", amount: 500, unit: "g" },
				{ ingredient: "Reisnudeln", amount: 200, unit: "g" },
				{ ingredient: "Rindfleisch (dünn)", amount: 200, unit: "g" },
				{ ingredient: "Sternanis", amount: 3, unit: "Stück" },
				{ ingredient: "Ingwer", amount: 50, unit: "g" },
				{ ingredient: "Frühlingszwiebeln", amount: 3, unit: "Stück" },
			],
			portion: 4,
			nutritionalValues: [{ kcal: "360", protein: "24g", fat: "8g", carbohydrates: "48g" }],
			directions: "Knochen rösten und mit Wasser, Sternanis und Ingwer 2 Stunden auskochen. Brühe abseihen. Reisnudeln kochen. Dünnes Rindfleisch in Scheiben in die Schüssel legen. Heiße Brühe darüber gießen. Mit Kräutern und Sprossen garnieren.",
			tags: ["vietnamesisch", "suppe", "nudeln"],
			href: "https://images.getrecipekit.com/20250721214543-Pho-Bo-easy-schnell-vietnam-rezept2.jpg?aspect_ratio=4:3&quality=90&",
			time: 150,
			comments: [],
			rating: [5, 5, 4, 5],
			categories: [catMap["fleisch"], catMap["suppe"]],
			user: user2._id,
		},
		{
			name: "Shakshuka",
			ingredients: [
				{ ingredient: "Eier", amount: 4, unit: "Stück" },
				{ ingredient: "Tomaten (gehackt)", amount: 800, unit: "g" },
				{ ingredient: "Paprika", amount: 2, unit: "Stück" },
				{ ingredient: "Zwiebel", amount: 1, unit: "Stück" },
				{ ingredient: "Kreuzkümmel", amount: 1, unit: "TL" },
				{ ingredient: "Feta", amount: 80, unit: "g" },
			],
			portion: 2,
			nutritionalValues: [{ kcal: "340", protein: "20g", fat: "18g", carbohydrates: "24g" }],
			directions: "Zwiebel und Paprika anbraten. Tomaten und Kreuzkümmel dazugeben, 10 Minuten einkochen. Mulden formen und Eier hineinschlagen. Zugedeckt 8 Minuten garen. Mit Feta bestreuen.",
			tags: ["orientalisch", "frühstück", "eier"],
			href: "https://www.gaumenfreundin.de/wp-content/uploads/2024/01/Shakshuka-Gaumenfreundin.jpg",
			time: 25,
			comments: [],
			rating: [5, 4, 4, 5],
			categories: [catMap["vegetarisch"]],
			user: user2._id,
		},
		{
			name: "Garnelen in Knoblauchöl",
			ingredients: [
				{ ingredient: "Garnelen", amount: 500, unit: "g" },
				{ ingredient: "Knoblauch", amount: 6, unit: "Zehen" },
				{ ingredient: "Olivenöl", amount: 100, unit: "ml" },
				{ ingredient: "Chili", amount: 1, unit: "Stück" },
				{ ingredient: "Petersilie", amount: 1, unit: "Bund" },
				{ ingredient: "Baguette", amount: 1, unit: "Stück" },
			],
			portion: 4,
			nutritionalValues: [{ kcal: "320", protein: "26g", fat: "20g", carbohydrates: "8g" }],
			directions: "Knoblauch in Scheiben schneiden. Olivenöl erhitzen, Knoblauch und Chili darin goldbraun braten. Garnelen dazugeben und 3 Minuten braten. Petersilie darüber streuen. Mit Baguette servieren.",
			tags: ["spanisch", "tapas", "garnelen"],
			href: "https://die-frau-am-grill.de/wp-content/uploads/gambas-pil-pil-garnelen-in-knoblauchoel.jpg",
			time: 15,
			comments: [],
			rating: [5, 5, 4],
			categories: [catMap["fisch"]],
			user: user2._id,
		},
		{
			name: "Flammkuchen",
			ingredients: [
				{ ingredient: "Pizzateig", amount: 1, unit: "Rolle" },
				{ ingredient: "Crème fraîche", amount: 200, unit: "g" },
				{ ingredient: "Speck", amount: 150, unit: "g" },
				{ ingredient: "Zwiebeln", amount: 2, unit: "Stück" },
				{ ingredient: "Muskatnuss", amount: 1, unit: "Prise" },
			],
			portion: 2,
			nutritionalValues: [{ kcal: "480", protein: "16g", fat: "28g", carbohydrates: "40g" }],
			directions: "Teig dünn ausrollen. Crème fraîche mit Muskat verrühren und auf dem Teig verstreichen. Zwiebeln in Ringe schneiden und mit Speckwürfeln darauf verteilen. Bei 220°C 12 Minuten knusprig backen.",
			tags: ["elsässisch", "flammkuchen", "schnell"],
			href: "https://www.einfachbacken.de/sites/einfachbacken.de/files/styles/1946_1460/public/2020-04/flammkuchen.jpg?h=4521fff0&itok=_XHz7Rny",
			time: 20,
			comments: [],
			rating: [4, 5, 5, 4],
			categories: [catMap["fleisch"]],
			user: user2._id,
		},
	]);
	console.log(`Created ${recipes.length} recipes`);
	
	await mongoose.disconnect();
	console.log("Seed complete");
}

seed().catch((err) => {
	console.error("Seed failed:", err);
	process.exit(1);
});
