services:

  guestbook:
    build: ./Gaestebuch

    volumes:
      - ./Gaestebuch/static:/static
      - ./Gaestebuch/templates:/templates
      - ./Gaestebuch/app.py:/app.py

    ports:
      - "5000:5000"

  banking:
    build: ./Onlinebanking

    volumes:
      - ./Onlinebanking/static:/static
      - ./Onlinebanking/templates/login_page.html:/templates/login_page.html
      - ./Onlinebanking/templates/dashboard_page.vuln.html:/templates/dashboard_page.html
      - ./Onlinebanking/app.vuln.py:/app.py

    ports:
      - "5001:5001"
