events { worker_connections 128; }
http {
  server {
    listen 8443 ssl;
    ssl_certificate     /etc/nginx/cert.pem;
    ssl_certificate_key /etc/nginx/key.pem;
    client_max_body_size 512M;
    location / {
      proxy_pass http://sp:80;
      proxy_set_header Host 127.0.0.1:8443;
      proxy_set_header X-Forwarded-Proto https;
      proxy_set_header X-Forwarded-Host 127.0.0.1:8443;
      proxy_set_header X-Real-IP $remote_addr;
      proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    }
  }
}
